### PR TITLE
add sample enemy scene, enemy spawn system.

### PR DESCRIPTION
**Pull request by ghost**
created an enemy manager that will take in different spawn points and spawn enemies.

@alexgryan , this should be an easy merge....just hit "merge request"

### CODE REVIEW

**Comment by schmjdt** [comment]
Hey club,
Just thought I'd chime in here a bit...

Not sure who exactly will see this, but a couple things to note about vc
unity files:
You should be using a .gitignore tailored to unity which should include
library files.  Those do not need to be shared.  Only things that need to
be shared is Assets folder and project settings (and even these probably
not since people don't seem to keep their unity consistent with one
another).

Second, when using assets from store, even when free, good practice to
watch for licenses.  Even though this just being developed within the club,
as a single group, still may be good practice to understand for future.
Have to watch out for what is allowed to be shared and what isn't, again,
even if it free it may say you can't redistribute.  Which again, may be
fine here since just version controlling, but usually good practice to only
version control what will be released.  Some assets are for dev only and
not published, so may not need to be sourced.

Just my two cents.  Keep up the amazing work all.  It has been fun watching
from the shadows.
- Joe

**Comment by alexgryan** [comment]
Sorry about that! Got your message and I just merged your commit Angel.

**Comment by ghost** [comment]
Thanks @alexgryan .

@schmjdt ,
thanks for the input, there is a .gitignore tailored to Unity in the repo, was there something in my merge that needs to be added to the .gitignore ?

**Comment by schmjdt** [comment]
Hmmm, OK.  I just don't remember the library folder being apart of it.  I
could be remembering wrong.

**Comment by ghost** [comment]
@schmjdt 

You are correct, Library was in the .gitignore, but the .gitignore was in the root directory so it wasn't seeing the Library folder.  I fixed it in master, and removed Library from source control.

Thanks for catching that.

**Comment by schmjdt** [comment]
Nice!  Just helps on saving space and quicker pulls.  Thanks.

**Pull request merged**
