### PR TITLE
Enemy spawner

### PR DESCRIPTION
**Pull request by ghost**
Updated the enemy spawning system.
- Enemy spawner can not take damage, when it reaches zero it gets destroyed.

### CODE REVIEW

**Comment by ghost** [comment]
@etang4 , feel free to give feedback on the updates before Friday if you'd like.

**Comment by schmjdt** [comment]
@skinnyMan , hey there, just wanted to give a suggestion... If the enemy spawners only way to receive damage to health is via the TakeDamage method (which it probably should be), then no reason to have to check for health in the update function every frame.  Can just do the destroy (or better yet, call another function to deal with death)  from the TakeDamage function where you check health already.  Just a way to save a bit of cycles.   Also, probably should be <= 0, unless you have different mechanics for at 0.

**Comment by ghost** [comment]
Thanks @schmjdt, took your feedback on the way I was checking for health <= 0 and implemented it.

**Comment by etang4** [comment]
Thanks @schmjdt for the feedback. Looks good Angel.

**Comment by ghost** [comment]
Sweet.

**Comment by alexgryan** [comment]
Looks good! I will merge now.

**Pull request merged**
