### PR TITLE
Enemy spawner fix

### PR DESCRIPTION
**Pull request by ghost**
Fixes issue #5, also makes it easier to layout spawn points. Just add the prefab to scene and it's ready to go.

### CODE REVIEW

**Comment by ghost** [comment]
fixes #5

**Comment by ghost** [comment]
@alexgryan Looks like this has run into a conflict, I'll take care of the conflict before you merge this.

Thanks.

**Comment by alexgryan** [comment]
@skinnyMan Yeah I think it's bc of stuff I created before the pull request. There are a couple of extra prefabs in there now

**Comment by ghost** [comment]
yea, it looks like we both did work to the enemy_spawner prefab. I'll take a look later on today.

Thanks.

**Comment by ghost** [comment]
@alexgryan I think the conflict is taken care of now. can you checkout this branch and verify that your door level is just the way you left it? the enemy spawners are now red, and don't require separate spawning points.

If you you like it, then it should merge with no issues.

thanks.

**Comment by alexgryan** [comment]
@skinnyMan Thanks it looks good I approve!

**Pull request merged**
