### PR TITLE
Tileset Materials

### PR DESCRIPTION
**Pull request by alexgryan**
Floor Prefab created.
Player1 Prefab created.
Wall Prefab created.
InputManager reconfigured for Player1

### CODE REVIEW

**Comment by alexgryan** [comment]
Eric are you cool with my pull request?

**Comment by etang4** [comment]
@alexgryan if you think you're good then do it. Don't need my permission :+1:

**Comment by alexgryan** [comment]
@etang4 you cool with pull request?

**Comment by alexgryan** [comment]
kewl beans

**Comment by schmjdt** [comment]
"@alexgryan if you think you're good then do it. Don't need my permission"

Tsk tsk tsk Eric.  That's the whole point of git and code reviews.  To get
a second, third, ect. pairs of eyes.
The person who submits a merge/pull request technically shouldn't be one
who approves it.
Just saying.  ^_^

**Comment by etang4** [comment]
@schmjdt true true. Didn't think too much into that. I was purely looking at it from a video game director point of view and not as a fellow programmer. @alexgryan if you want me to code review for you in the future, just be sure to comment it. Otherwise I will treat it from a director point of view.

**Comment by alexgryan** [comment]
kk bruh

**Pull request closed without merging**
